#Image id: ami-0f5ee92e2d63afc18
#SSH Key: gst-ssh-key
Parameters: 
    UbuntuImageId: 
        Type: String
    KeyPairName:
        Type: String

Resources:
    InvoiceEc2:
        Type: AWS::EC2::Instance
        Properties:
            UserData:
                Fn::Base64: !Sub |
                   #!/bin/bash
                   
                   sudo apt update
                   sudo apt install default-jdk
                   sudo apt update
                   sudo apt install maven

            KeyName: !Ref KeyPairName
            InstanceType: t2.micro
            SecurityGroups:
             - !Ref InvoiceSecurityGroup
            ImageId: !Ref UbuntuImageId
            Tags:
              - Key: Name
                Value: "gst-client-ec2"
    InvoiceSecurityGroup:
        Type: AWS::EC2::SecurityGroup
        Properties:
            GroupDescription: Allowing SSH from anywhere
            SecurityGroupIngress:
               - IpProtocol: tcp    
                 ToPort: '22'
                 FromPort: '22'
                 CidrIp: 0.0.0.0/0
               - IpProtocol: tcp    
                 ToPort: '80'
                 FromPort: '80'
                 CidrIp: 0.0.0.0/0
               - IpProtocol: tcp
                 ToPort: '443'
                 FromPort: '443'
                 CidrIp: 0.0.0.0/0